sudo: required
language: java
jdk: openjdk14

services:
  - mysql

script:
  - cd medihub-api
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=matijapetrovic_medihub -Dsonar.organization=matijapetrovic -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
addons:
  sonarcloud:
    organization: "matijapetrovic"
    token: $SONAR_TOKEN

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: medihub-app