sudo: required
language: java
jdk: openjdk14

services:
  - postgresql

before_install:
  - chmod +x mvnw

script:
  - cd medihub-api && mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: medihub-app